### ISSUE TITLE
Overlayfs

### ISSUE THREAD

**Issue by mibodhi** [davidedg/NAS-NSA325-mod#1]
Hi Davide!

I'tried to follow your example for initramfs script (init-bottom). There was a syntax change in mounting rw rootfs on top of  the ro rootfs in recent overlay fs. Still trying to adapt this script. Wonder if you have plan to do that?

Thx, 
bodhi

**Comment by davidedg** [comment]
Hi Bodhi,

which kernel version are you working this on ? still 3.xx or 4.x already?
Last time I tried it was on kernel 3.14, and I had to merge overlayfs tree from mszeredi's.
I've sent you my skype contact to discuss it faster.

**Comment by mibodhi** [comment]
Hi Davide,

I'm using kernel 4.0 (http://forum.doozan.com/read.php?2,12096). And the overlay package is from mainline Debian.

I've just tested this new syntax mods to your script, and it works fine:

ROOT_RW_ROOT=/mnt/root-rw/rootfs
ROOT_RW_WORK=/mnt/root-rw/work

MOUNT_PARMS="-t overlay -o lowerdir=${ROOT_RO},upperdir=${ROOT_RW_ROOT},workdir=${ROOT_RW_WORK} overlay ${rootmnt}"

Please feel free to adapt this to your script, when you have time.

Thanks for an excellent script! it saved me countless hours researching this :)
-bodhi
